### ISSUE TITLE
Option to see latest apps

### ISSUE THREAD

**Issue by mivoligo** [UbuntuOpenStore/openstore-app#1]
It would be nice to see which apps are new in the store. Maybe we can have something like "What's new" in the discovery tab?

**Comment by wagafo** [comment]
+1 - It could also be the first category in the "Categories" window. But "What's new" in the main windows is probably better.

**Comment by bhdouglass** [comment]
Moved here: https://github.com/UbuntuOpenStore/openstore-meta/issues/42
