### ISSUE TITLE
[Wishlist] Open button near the top of the app

### ISSUE THREAD

**Issue by cibersheep** [UbuntuOpenStore/openstore-app#2]
It would be nice to have the Open button for the installed apps, in the app view. Now it has to be scrolled all the way down to reach it.
![imatge](https://cloud.githubusercontent.com/assets/6640041/26178267/983cc502-3b5d-11e7-8c31-dec895cffe2b.png)

**Comment by bhdouglass** [comment]
Moved to here: https://github.com/UbuntuOpenStore/openstore-meta/issues/41
